// AUTO-GENERATED by tools/scripts/sync-deployment.mjs — do not edit manually.
// Source: ponder/deployments/polygon.json
// Synced: 2026-07-08T13:08:50.201Z

import type { Address } from 'viem'

export const THETA_DEPLOYMENT = {
  network: 'polygon',
  chainId: 137,
  startBlock: 89872856,
  deployer: '0xDD7D64BFd13EF3b733374Fc8DE9B9C651487a15D' as Address,
  thetaSingleton: '0x2fda0becb20294dde846018e36b261cda4d38a3a' as Address,
  betToken: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f' as Address,
  azuroLP: '0x0fa7fb5407ea971694652e6e16c12a52625de1b8' as Address,
  azuroCore: '0xf9548be470a4e130c90cea8b179fcd66d2972ac7' as Address,
  rpcUrl: 'https://polygon-bor-rpc.publicnode.com',
  useMocks: false,
} as const

export const PONDER_GRAPHQL_URL =
  process.env.EXPO_PUBLIC_PONDER_URL ?? 'https://fitting-decreased-dim-hazardous.trycloudflare.com/graphql'
