/** Free test key from TheSportsDB docs; override with your own in .env for production. */
export const THE_SPORTS_DB_API_KEY =
  process.env.EXPO_PUBLIC_THESPORTSDB_API_KEY?.trim() || '3'

export const THE_SPORTS_DB_BASE = `https://www.thesportsdb.com/api/v1/json/${THE_SPORTS_DB_API_KEY}`

/** Azuro country slug → TheSportsDB `c=` param for league search */
export const AZURO_COUNTRY_TO_SPORTSDB: Record<string, string> = {
  argentina: 'Argentina',
  australia: 'Australia',
  austria: 'Austria',
  belgium: 'Belgium',
  brazil: 'Brazil',
  bulgaria: 'Bulgaria',
  chile: 'Chile',
  china: 'China',
  colombia: 'Colombia',
  croatia: 'Croatia',
  czechia: 'Czech Republic',
  'czech-republic': 'Czech Republic',
  denmark: 'Denmark',
  ecuador: 'Ecuador',
  egypt: 'Egypt',
  england: 'England',
  finland: 'Finland',
  france: 'France',
  germany: 'Germany',
  greece: 'Greece',
  hungary: 'Hungary',
  iceland: 'Iceland',
  india: 'India',
  indonesia: 'Indonesia',
  international: 'Europe',
  ireland: 'Ireland',
  israel: 'Israel',
  italy: 'Italy',
  japan: 'Japan',
  mexico: 'Mexico',
  netherlands: 'Netherlands',
  'northern-ireland': 'Northern Ireland',
  norway: 'Norway',
  paraguay: 'Paraguay',
  peru: 'Peru',
  poland: 'Poland',
  portugal: 'Portugal',
  romania: 'Romania',
  russia: 'Russia',
  scotland: 'Scotland',
  serbia: 'Serbia',
  slovakia: 'Slovakia',
  slovenia: 'Slovenia',
  'south-africa': 'South Africa',
  'south-korea': 'South Korea',
  spain: 'Spain',
  sweden: 'Sweden',
  switzerland: 'Switzerland',
  turkey: 'Turkey',
  ukraine: 'Ukraine',
  uruguay: 'Uruguay',
  usa: 'USA',
  wales: 'Wales',
}
