/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 0
 *

 */

import { initializeWorkerCore, ensureRPCSetup } from "file:///home/drone/projects/ThethaBet/apps/mobile/node_modules/@qvac/sdk/dist/server/worker-core.js";
import { registerPlugin } from "file:///home/drone/projects/ThethaBet/apps/mobile/node_modules/@qvac/sdk/dist/server/plugins/index.js";
import { getServerLogger } from "file:///home/drone/projects/ThethaBet/apps/mobile/node_modules/@qvac/sdk/dist/logging/index.js";



const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 0");



// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
