export const COMMANDS = {
  READY: 1,
  GET_IDENTITY: 2,
  LIST_CHANNELS: 3,
  CREATE_CHANNEL: 4,
  JOIN_CHANNEL: 5,
  SEND_MESSAGE: 6,
  GET_HISTORY: 7,
  SHARE_CHANNEL_KEY: 8,
  RECEIVE_CHANNEL_KEY: 9,
  SET_TIPSTER_PROFILE: 10,
  GET_TIPSTER_PROFILE: 11,
  MESSAGE_EVENT: 100,
}
