#!/usr/bin/env bash
# Local dev stack: Ponder on Polygon mainnet (+ optional Cloudflare tunnel for mobile device access).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Ponder 0.16.x requires Node >= 20.
# Try NVM if available, otherwise rely on system PATH.
if [ -f "${NVM_DIR:-$HOME/.nvm}/nvm.sh" ]; then
  # shellcheck source=/dev/null
  . "${NVM_DIR:-$HOME/.nvm}/nvm.sh"
  nvm use 20 2>/dev/null || true
fi

PONDER_NETWORK="${PONDER_NETWORK:-polygon}"
USE_TUNNEL="${USE_TUNNEL:-0}"
PONDER_RPC_URL_1="${PONDER_RPC_URL_1:-https://polygon.drpc.org}"
export PONDER_RPC_URL_1
TUNNEL_FILE="$REPO_ROOT/apps/mobile/src/config/tunnel.generated.ts"
PONDER_LOG="${TMPDIR:-/tmp}/thetabet-ponder.log"
TUNNEL_LOG="${TMPDIR:-/tmp}/thetabet-tunnel.log"

cleanup() {
  if [ -n "${PONDER_PID:-}" ] && kill -0 "$PONDER_PID" 2>/dev/null; then
    kill "$PONDER_PID" 2>/dev/null || true
  fi
  if [ -n "${TUNNEL_PID:-}" ] && kill -0 "$TUNNEL_PID" 2>/dev/null; then
    kill "$TUNNEL_PID" 2>/dev/null || true
  fi
}
trap cleanup INT TERM

write_tunnel_url() {
  local url="$1"
  cat > "$TUNNEL_FILE" <<EOF
// AUTO-GENERATED by tools/dev-stack.sh — Cloudflare tunnel to local Ponder.
export const PONDER_TUNNEL_URL = '${url}'
EOF
  local sync_net="polygon"
  [ "$PONDER_NETWORK" = "anvil" ] && sync_net="anvil"
  node "$REPO_ROOT/tools/scripts/sync-deployment.mjs" "$sync_net"
  echo "Tunnel URL written: ${url}"
}

setup_android_reverse() {
  if ! command -v adb >/dev/null 2>&1; then
    return 0
  fi
  if ! adb get-state >/dev/null 2>&1; then
    return 0
  fi
  adb reverse tcp:42069 tcp:42069 >/dev/null 2>&1 || true
  echo "adb reverse tcp:42069 → host Ponder (app uses http://127.0.0.1:42069/graphql on USB Android)"
}

ponder_health_ok() {
  curl -sf http://127.0.0.1:42069/health >/dev/null 2>&1
}

ponder_log_has_db_corruption() {
  [ -f "$PONDER_LOG" ] && grep -qE "RuntimeError: Aborted|could not seek to end of file|InitWalRecovery" "$PONDER_LOG" 2>/dev/null
}

stop_stale_ponder() {
  pkill -f "ponder/dist/esm/bin/ponder.js dev" 2>/dev/null || true
  pkill -f "ponder dev --disable-ui" 2>/dev/null || true
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    if ! ponder_health_ok; then
      return 0
    fi
    sleep 1
  done
  pkill -9 -f "ponder/dist/esm/bin/ponder.js dev" 2>/dev/null || true
  sleep 1
}

reset_ponder_db() {
  echo "Resetting local Ponder database (ponder/.ponder/pglite) ..."
  rm -rf "$REPO_ROOT/ponder/.ponder/pglite"
}

prepare_ponder_db() {
  if [ "${PONDER_RESET_DB:-0}" = "1" ]; then
    reset_ponder_db
    return 0
  fi
  if ponder_log_has_db_corruption; then
    reset_ponder_db
  fi
  return 0
}

truncate_ponder_log() {
  mkdir -p "$(dirname "$PONDER_LOG")"
  >"$PONDER_LOG"
}

launch_ponder() {
  cd "$REPO_ROOT/ponder"
  PONDER_NETWORK="$PONDER_NETWORK" npm run dev -- --disable-ui >>"$PONDER_LOG" 2>&1 &
  PONDER_PID=$!
}

wait_for_ponder_ready() {
  local attempts="${1:-90}"
  local i
  for ((i=1; i<=attempts; i++)); do
    if ponder_health_ok; then
      return 0
    fi
    if ponder_log_has_db_corruption; then
      return 2
    fi
    if [ -n "${PONDER_PID:-}" ] && ! kill -0 "$PONDER_PID" 2>/dev/null; then
      return 1
    fi
    sleep 1
  done
  return 1
}

start_ponder() {
  echo "Starting Ponder (PONDER_NETWORK=${PONDER_NETWORK}) ..."

  stop_stale_ponder

  if ponder_health_ok; then
    echo "Ponder ready at http://localhost:42069/graphql (already running)"
    PONDER_PID=""
    return 0
  fi

  prepare_ponder_db
  truncate_ponder_log

  launch_ponder

  wait_for_ponder_ready 90
  rc=$?
  if [ "$rc" -eq 0 ]; then
    echo "Ponder ready at http://localhost:42069/graphql"
    return 0
  fi

  if [ "$rc" -eq 2 ] || ponder_log_has_db_corruption; then
    echo "Ponder database looks corrupt - resetting and retrying once ..."
    stop_stale_ponder
    reset_ponder_db
    truncate_ponder_log
    launch_ponder
    if wait_for_ponder_ready 90; then
      echo "Ponder ready at http://localhost:42069/graphql"
      return 0
    fi
  fi

  stop_stale_ponder
  echo "Ponder failed to start — see $PONDER_LOG"
  tail -40 "$PONDER_LOG" || true
  echo ""
  echo "Try a clean reset: PONDER_RESET_DB=1 npm run dev:stack:tunnel"
  exit 1
}

start_tunnel() {
  if ! command -v cloudflared >/dev/null 2>&1; then
    echo "cloudflared not installed — skipping tunnel (set USE_TUNNEL=0 or install cloudflared)"
    return 0
  fi

  echo "Starting Cloudflare tunnel to Ponder ..."
  cloudflared tunnel --url http://127.0.0.1:42069 >"$TUNNEL_LOG" 2>&1 &
  TUNNEL_PID=$!

  for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45; do
    TUNNEL_URL=$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$TUNNEL_LOG" | head -1 || true)
    if [ -n "$TUNNEL_URL" ]; then
      write_tunnel_url "$TUNNEL_URL"
      return 0
    fi
    sleep 1
  done

  echo "Tunnel URL not detected — see $TUNNEL_LOG"
  tail -20 "$TUNNEL_LOG" || true
}

echo "ThetaBet dev stack"
echo "  repo:    $REPO_ROOT"
echo "  network: $PONDER_NETWORK"
echo "  tunnel:  $USE_TUNNEL"

start_ponder
setup_android_reverse

if [ "$USE_TUNNEL" = "1" ]; then
  start_tunnel
else
  SYNC_NET="polygon"
  [ "$PONDER_NETWORK" = "anvil" ] && SYNC_NET="anvil"
  node "$REPO_ROOT/tools/scripts/sync-deployment.mjs" "$SYNC_NET"
  echo "Local Ponder only — mobile uses http://localhost:42069 (emulator) or set USE_TUNNEL=1"
fi

echo ""
echo "Mobile: reload Metro / shake device after tunnel URL sync (URL changes each run)."
echo "Press Ctrl+C to stop (stops Ponder + tunnel — Profile tab will fail until you restart)."
echo "Ponder logs: ${PONDER_LOG}"

while true; do
  if ponder_health_ok; then
    sleep 3
    continue
  fi
  if [ -n "${PONDER_PID:-}" ] && kill -0 "$PONDER_PID" 2>/dev/null; then
    sleep 3
    continue
  fi
  echo ""
  echo "Ponder stopped unexpectedly — last log lines:"
  tail -50 "$PONDER_LOG" || true
  exit 1
done
